---
name: Release Charts

concurrency: release-charts

on:
  push:
    branches: [main]
    paths:
      - "charts/*/Chart.yaml"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "src"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "dest"
          ref: "gh-pages"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-{{ .Version }}"
        with:
          charts_dir: src/charts

      - name: Find packaged charts
        shell: bash
        run: |
          env | grep GITHUB
          pwd
          find .cr-release-packages -type f -name '*.tgz'
          for chart in .cr-release-packages/* ; do
              echo "$chart"
          done
