---
name: Release Charts

concurrency: release-charts

on:
  push:
    branches: [main]
    paths:
      - "charts/*/Chart.yaml"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-{{ .Name }}-{{ .Version }}"
        with:
          charts_dir: charts

      # Override index package location and upload to branch until https://github.com/helm/chart-releaser/pull/123 is merged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: gh-pages
          ref: gh-pages

      - name: Copy packaged charts to gh-pages branch
        shell: bash
        run: |
          for chart in .cr-release-packages/*.tgz ; do
              echo "Copying $chart"
              cp $chart gh-pages
          done

      - name: Push charts to gh-pages branch
        shell: bash
        working-directory: gh-pages
        run: |
          helm repo index . --url https://raw.githubusercontent.com/$GITHUB_REPOSITORY/gh-pages/
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "update from $GITHUB_SHA"
          git push
